---
apiVersion: v1
kind: Service
metadata:
  name: gogs-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
  {{- include "gogs.labels" . | indent 4 }}
  ports:
  - name: ssh
    protocol: TCP
    targetPort: 22
  - name: http
    protocol: TCP
    targetPort: 3000
